Menu dana
mhumetskyi/minesweeper pull request #8
Opened 2021-11-13 19:41 UTC by kimdana2005

Добавила меню "Гра"
Пункти меню:
- Початок гри
- Складніть:
    1. легко
    2. нормально
    3. складно
- Вихід

2021-11-24 15:41 UTC, Tarik669 approved these changes

2021-11-24 15:44 UTC, Tarik669 requested changes
Додати класси

2021-11-24 15:46 UTC, Tarik669 commented on Menu.py
> +cfrom tkinter import *
Зайва літера с
```suggestion
from tkinter import *
```

2021-12-05 12:00 UTC, mhumetskyi commented on main.py
> +from menu import MainMenu
Нема потреби в пістій стрічці тут
```suggestion
from menu import MainMenu
```

2021-12-05 12:05 UTC, Tarik669 approved these changes

2021-12-05 12:22 UTC, merged